name:                LIPS-USB
version:             0.1.0.0
github:              "githubuser/LIPS-USB"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/LIPS-USB#readme>

dependencies:
- base >= 4.7 && < 5
- random
- mwc-random
- parsec
- mtl
- containers
- pretty-tree
- bytestring
- text
- tasty
- tasty-hunit
- tasty-hspec
- time
- array
- mmorph
library:
  source-dirs: src

executables:
  LIPS-USB-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LIPS-USB

tests:
  LIPS-USB-test:
    main:                LibTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LIPS-USB
